import { ProductList, Product } from '../types/product-type';

export const mockProductList: ProductList = [
  {
    id: 1,
    name: 'Stratocaster',
    rentPricePerDay: 12000,
    imageUrl: '/img/effector/effector2.webp',
    shopName: 'Guitar Shop A',
    shopId: 1,
    isRentable: true,
    isPurchasable: false,
    isDemoable: true,
    isLiked: false,
  },
  {
    id: 2,
    name: 'Les Paul',
    rentPricePerDay: 15000,
    imageUrl: '/img/effector/effector3.webp',
    shopName: 'Guitar Shop B',
    shopId: 2,
    isRentable: true,
    isPurchasable: true,
    isDemoable: false,
    isLiked: true,
  },
  {
    id: 3,
    name: 'Telecaster',
    rentPricePerDay: 11000,
    imageUrl: '/img/effector/effector4.webp',
    shopName: 'Guitar Shop C',
    shopId: 3,
    isRentable: false,
    isPurchasable: true,
    isDemoable: true,
    isLiked: false,
  },
  {
    id: 4,
    name: 'Jazz Bass',
    rentPricePerDay: 13000,
    imageUrl: '/img/effector/effector5.webp',
    shopName: 'Bass Shop',
    shopId: 4,
    isRentable: true,
    isPurchasable: false,
    isDemoable: true,
    isLiked: true,
  },
  {
    id: 5,
    name: 'Precision Bass',
    rentPricePerDay: 12500,
    imageUrl: '/img/effector/effector6.webp',
    shopName: 'Bass Shop',
    shopId: 4,
    isRentable: true,
    isPurchasable: true,
    isDemoable: false,
    isLiked: false,
  },
  {
    id: 6,
    name: 'SG',
    rentPricePerDay: 14000,
    imageUrl: '/img/effector/effector7.webp',
    shopName: 'Guitar Shop D',
    shopId: 5,
    isRentable: false,
    isPurchasable: true,
    isDemoable: true,
    isLiked: true,
  },
  {
    id: 7,
    name: 'Explorer',
    rentPricePerDay: 13500,
    imageUrl: '/img/effector/effector8.webp',
    shopName: 'Guitar Shop E',
    shopId: 6,
    isRentable: true,
    isPurchasable: false,
    isDemoable: false,
    isLiked: false,
  },
  {
    id: 8,
    name: 'Flying V',
    rentPricePerDay: 14500,
    imageUrl: '/img/effector/effector9.webp',
    shopName: 'Guitar Shop F',
    shopId: 7,
    isRentable: true,
    isPurchasable: true,
    isDemoable: true,
    isLiked: true,
  },
  {
    id: 9,
    name: 'Hollow Body',
    rentPricePerDay: 16000,
    imageUrl: '/img/effector/effector10.webp',
    shopName: 'Jazz Shop',
    shopId: 8,
    isRentable: false,
    isPurchasable: true,
    isDemoable: false,
    isLiked: false,
  },
  {
    id: 10,
    name: 'Acoustic',
    rentPricePerDay: 10000,
    imageUrl: '/img/effector/effector11.webp',
    shopName: 'Acoustic Shop',
    shopId: 9,
    isRentable: true,
    isPurchasable: false,
    isDemoable: true,
    isLiked: true,
  },
  {
    id: 11,
    name: 'Classic Guitar',
    rentPricePerDay: 9000,
    imageUrl: '/img/effector/effector12.webp',
    shopName: 'Classic Shop',
    shopId: 10,
    isRentable: true,
    isPurchasable: true,
    isDemoable: false,
    isLiked: false,
  },
  {
    id: 12,
    name: 'Ukulele',
    rentPricePerDay: 8000,
    imageUrl: '/img/effector/effector13.webp',
    shopName: 'Ukulele Shop',
    shopId: 11,
    isRentable: false,
    isPurchasable: true,
    isDemoable: true,
    isLiked: true,
  },
  {
    id: 13,
    name: 'Mandolin',
    rentPricePerDay: 9500,
    imageUrl: '/img/effector/effector14.webp',
    shopName: 'Mandolin Shop',
    shopId: 12,
    isRentable: true,
    isPurchasable: false,
    isDemoable: false,
    isLiked: false,
  },
  {
    id: 14,
    name: 'Banjo',
    rentPricePerDay: 10500,
    imageUrl: '/img/effector/effector15.webp',
    shopName: 'Banjo Shop',
    shopId: 13,
    isRentable: true,
    isPurchasable: true,
    isDemoable: true,
    isLiked: true,
  },
  {
    id: 15,
    name: 'Resonator',
    rentPricePerDay: 11500,
    imageUrl: '/img/effector/effector16.webp',
    shopName: 'Resonator Shop',
    shopId: 14,
    isRentable: false,
    isPurchasable: true,
    isDemoable: false,
    isLiked: false,
  },
  {
    id: 16,
    name: 'Lap Steel',
    rentPricePerDay: 12500,
    imageUrl: '/img/effector/effector17.webp',
    shopName: 'Lap Steel Shop',
    shopId: 15,
    isRentable: true,
    isPurchasable: false,
    isDemoable: true,
    isLiked: true,
  },
  {
    id: 17,
    name: 'Pedal Steel',
    rentPricePerDay: 13500,
    imageUrl: '/img/effector/effector18.webp',
    shopName: 'Pedal Steel Shop',
    shopId: 16,
    isRentable: true,
    isPurchasable: true,
    isDemoable: false,
    isLiked: false,
  },
  {
    id: 18,
    name: 'Baritone',
    rentPricePerDay: 14500,
    imageUrl: '/img/effector/effector19.webp',
    shopName: 'Baritone Shop',
    shopId: 17,
    isRentable: false,
    isPurchasable: true,
    isDemoable: true,
    isLiked: true,
  },
  {
    id: 19,
    name: '12-String',
    rentPricePerDay: 15500,
    imageUrl: '/img/effector/effector20.webp',
    shopName: '12-String Shop',
    shopId: 18,
    isRentable: true,
    isPurchasable: false,
    isDemoable: false,
    isLiked: false,
  },
  {
    id: 20,
    name: 'Double Neck',
    rentPricePerDay: 16500,
    imageUrl: '/img/effector/effector21.webp',
    shopName: 'Double Neck Shop',
    shopId: 19,
    isRentable: true,
    isPurchasable: true,
    isDemoable: true,
    isLiked: true,
  },
  {
    id: 21,
    name: 'Travel Guitar',
    rentPricePerDay: 9500,
    imageUrl: '/img/effector/effector22.webp',
    shopName: 'Travel Shop',
    shopId: 20,
    isRentable: false,
    isPurchasable: true,
    isDemoable: false,
    isLiked: false,
  },
  {
    id: 22,
    name: 'Mini Guitar',
    rentPricePerDay: 8500,
    imageUrl: '/img/effector/effector23.webp',
    shopName: 'Mini Shop',
    shopId: 21,
    isRentable: true,
    isPurchasable: false,
    isDemoable: true,
    isLiked: true,
  },
  {
    id: 23,
    name: 'Silent Guitar',
    rentPricePerDay: 10500,
    imageUrl: '/img/effector/effector24.webp',
    shopName: 'Silent Shop',
    shopId: 22,
    isRentable: true,
    isPurchasable: true,
    isDemoable: false,
    isLiked: false,
  },
  {
    id: 24,
    name: 'Headless Guitar',
    rentPricePerDay: 11500,
    imageUrl: '/img/effector/effector25.webp',
    shopName: 'Headless Shop',
    shopId: 23,
    isRentable: false,
    isPurchasable: true,
    isDemoable: true,
    isLiked: true,
  },
  {
    id: 25,
    name: 'Archtop',
    rentPricePerDay: 12500,
    imageUrl: '/img/effector/effector26.webp',
    shopName: 'Archtop Shop',
    shopId: 24,
    isRentable: true,
    isPurchasable: false,
    isDemoable: false,
    isLiked: false,
  },
  {
    id: 26,
    name: 'Semi-Hollow',
    rentPricePerDay: 13500,
    imageUrl: '/img/effector/effector27.webp',
    shopName: 'Semi-Hollow Shop',
    shopId: 25,
    isRentable: true,
    isPurchasable: true,
    isDemoable: true,
    isLiked: true,
  },
  {
    id: 27,
    name: 'Superstrat',
    rentPricePerDay: 14500,
    imageUrl: '/img/effector/effector28.webp',
    shopName: 'Superstrat Shop',
    shopId: 26,
    isRentable: false,
    isPurchasable: true,
    isDemoable: false,
    isLiked: false,
  },
  {
    id: 28,
    name: 'Offset',
    rentPricePerDay: 15500,
    imageUrl: '/img/effector/effector29.webp',
    shopName: 'Offset Shop',
    shopId: 27,
    isRentable: true,
    isPurchasable: false,
    isDemoable: true,
    isLiked: true,
  },
  {
    id: 29,
    name: 'Baritone Acoustic',
    rentPricePerDay: 16500,
    imageUrl: '/img/effector/effector30.webp',
    shopName: 'Baritone Acoustic Shop',
    shopId: 28,
    isRentable: true,
    isPurchasable: true,
    isDemoable: false,
    isLiked: false,
  },
  {
    id: 30,
    name: 'Multi-Neck',
    rentPricePerDay: 17500,
    imageUrl: '/img/effector/effector1.webp',
    shopName: 'Multi-Neck Shop',
    shopId: 29,
    isRentable: false,
    isPurchasable: true,
    isDemoable: true,
    isLiked: true,
  },
];
